services:
  books-backend:
    container_name: books-be
    depends_on:
      - books-db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DEPLOY=release
    restart: unless-stopped

  books-db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: dockeruser
      POSTGRES_PASSWORD: dbpassword
      POSTGRES_DB: books-docker-db
